### PR TITLE
Publish version number for JS

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-valo-theme/40)

### CODE REVIEW

**Comment by jouni** [comment]
All the individual element style modules are already moved / being moved to their corresponding element repos.

Instead of importing version.html in the element style modules, I would import in the utility style modules (color, typography, sizing, spacing, style). All the elements import at least one of them.

**Comment by Artur-** [comment]
Moved to the style modules

**Review by jouni — CHANGES_REQUESTED** [review]
Do not add to `badge.html` and `menu-overlay.html`, as those are not part of the base style modules, but actual implementations for specific elements/components.

Import missing from `icons.html`.

Are there any instructions when/how to update the version (maybe add to readme)?

**Comment by Artur-** [comment]
Updated

**Review by jouni — APPROVED** [review]

**Comment by jouni** [comment]
Won’t bother using Reviewable. LGTM.

**Pull request merged**
