### PR TITLE
Workaround mask-image CSS property to prevent crash in Edge

### LINKED ISSUE #45: importing Valo theme for vaadin-text-field crashes the page in the latest Edge
Using a Valo-themed vaadin-text-field crashes the entire web page in the latest released Edge version (possibly a browser bug).

Screen cast of the issue: https://youtu.be/PPb9n004GBQ
JS Fiddle (last known working version): https://jsfiddle.net/mg6gbq20/2/
JS Fiddle (first known broken version): https://jsfiddle.net/mg6gbq20/1/
JS Fiddle (the latest released version is still broken): https://jsfiddle.net/mg6gbq20/3/

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #45

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-valo-styles/48)

### CODE REVIEW

**Comment by vicsstar** [comment]
Looks like vaadin-combo-box and vaadin-dropdown-menu are still crashing on Edge.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-:-L2_S4-C19XYmWJ5dvQv:bkza00h)*

**Comment by tomivirkki** [comment]
My guess is it's because by default bower is installing the latest released alphas and we haven't yet released new ones with the issues fixed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-:-L2_VbRAAPiqlvfGRYOQ:b5y6x2q)*

**Comment by vicsstar** [comment]
*[mixins/menu-overlay.html, line 59 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-L2_Vrm6dAnd4K8Rq0_p:-L2_Vrm6dAnd4K8Rq0_q:by0y3hm) ([raw file](https://github.com/vaadin/vaadin-valo-styles/blob/ca78336aa586794cdef1a770d085d68034bdbff1/mixins/menu-overlay.html#L59)):*
> ```HTML
>           */
>           -webkit-mask-image: linear-gradient(#000, transparent 40px, transparent calc(100% - 40px), #000);
>           mask-image: linear-gradient(#000, transparent 40px, transparent calc(100% - 40px), #000);
> ```

Is this not supposed to be in a Mozilla-only media query? Think it's still the one responsible for the crashes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48)*

**Comment by web-padawan** [comment]
Right, both of these elements needs proper releases for valo-styles and text-field. But this PR can be closed since we switch to lumo-styles now.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mixins/menu-overlay.html, line 59 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-L2_Vrm6dAnd4K8Rq0_p:-L2_WG9uUzee7toXBNxf:b-tis3jn) ([raw file](https://github.com/vaadin/vaadin-valo-styles/blob/ca78336aa586794cdef1a770d085d68034bdbff1/mixins/menu-overlay.html#L59)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Is this not supposed to be in a Mozilla-only media query? Think it's still the one responsible for the crashes.
</blockquote></details>

Yes, I will update the lumo PR accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-:-L2_Vw6enRqwvJgL4xo2:b-eznjci)*

**Comment by vicsstar** [comment]
> er is installing the latest released alp
Yea but, I copied the CSS fix directly to my bower dependencies instances.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-:-L2_WAPwV5JfpH4bWlXI:b-d1ymd8)*

**Comment by vicsstar** [comment]
*[mixins/menu-overlay.html, line 59 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48#-L2_Vrm6dAnd4K8Rq0_p:-L2_WWrqcT5HUeAmFidG:b-837i3v) ([raw file](https://github.com/vaadin/vaadin-valo-styles/blob/ca78336aa586794cdef1a770d085d68034bdbff1/mixins/menu-overlay.html#L59)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Yes, I will update the lumo PR accordingly.
</blockquote></details>

Okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48)*

**Comment by vicsstar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-valo-styles/48)*

**Comment by web-padawan** [comment]
Superseded by vaadin/vaadin-lumo-styles#1

**Pull request closed without merging**
